# Generated by Django 4.0.4 on 2022-05-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('short_description', models.TextField(verbose_name='Краткая характеристика')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100, verbose_name='Телефон')),
                ('store', models.CharField(max_length=100, verbose_name='Магазин')),
                ('birth_day', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('description', models.TextField(null=True, verbose_name='Краткое описание')),
                ('size', models.FloatField(null=True, verbose_name='Объем')),
                ('fatness', models.FloatField(null=True, verbose_name='Жирность')),
                ('price', models.FloatField(verbose_name='Цена продажи')),
                ('image_url', models.TextField(verbose_name='Изображение')),
                ('good_url', models.TextField(verbose_name='Ссылка на товар')),
            ],
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
